version: '3.7'

services:
  db:
    image: postgres
    container_name: wiiQare-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wiiQare-db
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - wiiqare-net
  # redis:
  #   container_name: wiiQare-redis
  #   image: 'bitnami/redis:latest'
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #     - REDIS_PASSWORD=somePassword
  #   env_file:
  #     - .env
  #   volumes:
  #     - 'redis_data:/bitnami/redis/data'
  #   networks:
  #     - wiiqare-net
  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio_data:/data'
    networks:
      - wiiqare-net

volumes:
  redis_data:
    driver: local
  data:
    driver: local
  minio_data:
    driver: local

networks:
  wiiqare-net:
    driver: bridge
